version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
        
  app:
    container_name: golestan_api
    depends_on:
      - mongo_db
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
       PORT: 8080
       DATABASE_URI: mongodb://mongo_db:27017
       ACCESS_TOKEN_SECRET: fhsg54gdDFGDFdl53kigfdgew573405hfgdfg37048fh7380h7348hf837gdf4FDSGW%$^GFgfdgdgfDGSF%$^FHJUIO&*$$tryghgfdg

volumes:
  mongo_db: {}